# Image de base
FROM debian:bookworm-slim

# Metadata
LABEL maintainer="corentin_b"
LABEL version="v1.0"
LABEL description="Image LAMP Apache PHP"

# Mode non interactif
ENV DEBIAN_FRONTEND=noninteractive

# Installation Apache + PHP
RUN apt update && apt install -y \
    apache2 \
    php \
    libapache2-mod-php \
    && apt clean

# Supprimer page par défaut
RUN rm -rf /var/www/html/*

# Copier site local
COPY ./mywebsite /var/www/html

# Définir dossier de travail
WORKDIR /var/www/html

# Exposer port
EXPOSE 80

# Lancer Apache
CMD ["apachectl", "-D", "FOREGROUND"]